# Generated by Django 3.1.7 on 2021-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ieltsstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ieltstest',
            fields=[
                ('sublevel', models.IntegerField(blank=True, db_column='SubLevel', null=True)),
                ('qnumber', models.IntegerField(blank=True, db_column='QNumber', primary_key=True, serialize=False)),
                ('qcontent', models.TextField(blank=True, db_column='QContent', null=True)),
                ('answera', models.TextField(blank=True, db_column='AnswerA', null=True)),
                ('answerb', models.TextField(blank=True, db_column='AnswerB', null=True)),
                ('answerc', models.TextField(blank=True, db_column='AnswerC', null=True)),
                ('answerd', models.TextField(blank=True, db_column='AnswerD', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='CorrectAnswer', null=True)),
                ('passed', models.IntegerField(blank=True, db_column='Passed', null=True)),
            ],
        ),
    ]
