# Generated by Django 3.2 on 2021-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsstories',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='answera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='answerb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='answerc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='answerd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='qcontent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='qnumber',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ieltstest',
            name='sublevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
