# Generated by Django 3.2 on 2021-04-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_lesson_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
    ]
